version: '3.8'

services:
  client:
    image: node:18-alpine
    container_name: learnato-client-dev
    command: sh -c "npm install && npm run dev"
    working_dir: /app/client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
    environment:
      - NODE_ENV=development
      - VITE_SERVER_HOST=true
    networks:
      - learnato-net

  server:
    image: node:18-alpine
    container_name: learnato-server-dev
    command: sh -c "npm install && npm run dev"
    working_dir: /app/server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app/server
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_KEY=${COOKIE_KEY}
    networks:
      - learnato-net
    depends_on:
      - client

networks:
  learnato-net:
    driver: bridge